import Database from 'better-sqlite3';
const db = new Database('./cafe.db');
try { db.exec("ALTER TABLE menu_items ADD COLUMN category TEXT DEFAULT 'Diger'"); } catch(e) {}
const insert = db.prepare("INSERT INTO menu_items (name, desc, img, price, eta, category) VALUES (?, ?, ?, ?, ?, ?)");
insert.run("Caffe Latte","Espresso ve ipeksi sut kopugu","☕",42,8,"Sicak Icecekler");
insert.run("Cappuccino","Yogun espresso ve kadifemsi sut kopugu","☕",40,7,"Sicak Icecekler");
insert.run("Caramel Macchiato","Karamel surubu, sut ve espresso katlari","🍯",48,10,"Sicak Icecekler");
insert.run("Turk Kahvesi","Geleneksel kopuklu Turk kahvesi","🫖",35,12,"Sicak Icecekler");
insert.run("Filtre Kahve","Gunluk taze cekilmis filtre kahve","☕",38,5,"Sicak Icecekler");
insert.run("Salep","Geleneksel Osmanli salepli sicak icecegi","🌸",45,8,"Sicak Icecekler");
insert.run("Sicak Cikolata","Kremali sicak Belcika cikolatasi","🍫",50,8,"Sicak Icecekler");
insert.run("Iced Americano","Buzlu keskin espresso, serin serinlik","🧊",40,5,"Soguk Icecekler");
insert.run("Cold Brew","18 saatte demlenen soguk kahve, dusuk asidite","🥤",52,10,"Soguk Icecekler");
insert.run("Mango Smoothie","Taze mango, yogurt ve bal karisimi","🥭",55,8,"Soguk Icecekler");
insert.run("Limonata","Taze sikilmis limon, nane ve seker","🍋",35,5,"Soguk Icecekler");
insert.run("Matcha Latte","Japon matcha tozu, buharda isitilmis sut","🍵",55,8,"Soguk Icecekler");
insert.run("Strawberry Shake","Taze cilek, dondurma ve sut karisimi","🍓",60,8,"Soguk Icecekler");
insert.run("Avocado Toast","Eksi mayali ekmekte avokado, kirmizi biber","🥑",75,15,"Kahvalti");
insert.run("Klasik Serpme","Peynir, zeytin, domates, salatalik cesitleri","🧀",95,20,"Kahvalti");
insert.run("Simit Peynir","Taze firin simit, beyaz peynir ve zeytin","🥨",45,10,"Kahvalti");
insert.run("Menemen","Domates, biber ve yumurta kavurmasi","🍳",65,15,"Kahvalti");
insert.run("Club Sandwich","Tavuk, marul, domates, mayonez, ekmek","🥪",85,20,"Ana Yemekler");
insert.run("Caesar Salata","Romaine marul, parmesan, kruton, sos","🥗",70,12,"Ana Yemekler");
insert.run("Margherita Pizza","San Marzano domates, mozzarella, fesle gen","🍕",110,25,"Ana Yemekler");
insert.run("Tavuk Wrap","Izgara tavuk, roka, domates, sarimsakli sos","🌯",80,18,"Ana Yemekler");
insert.run("Cheesecake","New York usulu yogun kremali cheesecake","🍰",65,10,"Tatlilar");
insert.run("Tiramisu","Italyan usulu mascarpone ve espresso tatlisi","🎂",70,10,"Tatlilar");
insert.run("Brownie Dondurma","Sicak cikolatali brownie ve vanilyal dondurma","🍫",75,12,"Tatlilar");
const count = db.prepare("SELECT COUNT(*) as c FROM menu_items").get();
console.log("Seeded items:", count.c);
db.close();
